spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hse_sc
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver

  cloud:
    openfeign:
      client:
        config:
          calendarific:
            url: https://calendarific.com/api/v2

#  h2:
#    console.enabled: true
